name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build_and_release:
    name: uruntime
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install deps
        run: >
          sudo bash -c 'apt update && apt install binutils curl musl-tools qemu-user-static llvm -y';
          rustup component add rust-src --toolchain nightly;
          cargo install cross;

      - name: Build
        run: cargo xtask all

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/uruntime*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
