name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: uruntime
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install deps
        run: >
          sudo bash -c 'apt update && apt install binutils curl musl-tools qemu-user-static -y';
          rustup component add rust-src --toolchain nightly;
          cargo install cross;

      - name: Build x86_64
        run: >
          echo ==============================================x86_64==============================================;
          cargo clean;

          echo runimage;
          cargo +nightly build --release --target x86_64-unknown-linux-musl -Z unstable-options -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort;
          mv target/x86_64-unknown-linux-musl/release/uruntime uruntime-runimage-x86_64;

          echo runimage-squashfs;
          cargo +nightly build --release --target x86_64-unknown-linux-musl -Z unstable-options -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --no-default-features --features squashfs;
          mv target/x86_64-unknown-linux-musl/release/uruntime uruntime-runimage-squashfs-x86_64;

          echo runimage-dwarfs;
          cargo +nightly build --release --target x86_64-unknown-linux-musl -Z unstable-options -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --no-default-features --features dwarfs;
          mv target/x86_64-unknown-linux-musl/release/uruntime uruntime-runimage-dwarfs-x86_64;

          echo appimage;
          cargo +nightly build --release --target x86_64-unknown-linux-musl -Z unstable-options -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --features appimage;
          mv target/x86_64-unknown-linux-musl/release/uruntime uruntime-appimage-x86_64;

          echo appimage-squashfs;
          cargo +nightly build --release --target x86_64-unknown-linux-musl -Z unstable-options -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --no-default-features --features appimage,squashfs;
          mv target/x86_64-unknown-linux-musl/release/uruntime uruntime-appimage-squashfs-x86_64;

          echo appimage-dwarfs;
          cargo +nightly build --release --target x86_64-unknown-linux-musl -Z unstable-options -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --no-default-features --features appimage,dwarfs;
          mv target/x86_64-unknown-linux-musl/release/uruntime uruntime-appimage-dwarfs-x86_64;

      - name: Strip x86_64
        run: >
          echo ==============================================strip==============================================;
          strip -s -R .comment -R .gnu.version --strip-unneeded uruntime-*-x86_64 ;

      - name: Build aarch64
        run: >
          echo ==============================================aarch64==============================================;
          cargo clean;

          echo runimage;
          cross build --release --target aarch64-unknown-linux-musl;
          mv target/aarch64-unknown-linux-musl/release/uruntime uruntime-runimage-aarch64;

          echo runimage-squashfs;
          cross build --release --target aarch64-unknown-linux-musl --no-default-features --features squashfs;
          mv target/aarch64-unknown-linux-musl/release/uruntime uruntime-runimage-squashfs-aarch64;

          echo runimage-dwarfs;
          cross build --release --target aarch64-unknown-linux-musl --no-default-features --features dwarfs;
          mv target/aarch64-unknown-linux-musl/release/uruntime uruntime-runimage-dwarfs-aarch64;

          echo appimage;
          cross build --release --target aarch64-unknown-linux-musl --features appimage;
          mv target/aarch64-unknown-linux-musl/release/uruntime uruntime-appimage-aarch64;

          echo appimage-squashfs;
          cross build --release --target aarch64-unknown-linux-musl --no-default-features --features appimage,squashfs;
          mv target/aarch64-unknown-linux-musl/release/uruntime uruntime-appimage-squashfs-aarch64;

          echo appimage-dwarfs;
          cross build --release --target aarch64-unknown-linux-musl --no-default-features --features appimage,dwarfs;
          mv target/aarch64-unknown-linux-musl/release/uruntime uruntime-appimage-dwarfs-aarch64;

      - name: Add magic
        run: >
          echo ==============================================RI==============================================;
          ls -1 uruntime-runimage*|xargs -I {} sh -c "echo -ne 'RI\x02'|dd of={} bs=1 count=3 seek=8 conv=notrunc";

          echo ==============================================AI==============================================;
          ls -1 uruntime-appimage*|xargs -I {} sh -c "echo -ne 'AI\x02'|dd of={} bs=1 count=3 seek=8 conv=notrunc";

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: uruntime*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
